# Generated by Django 2.1.4 on 2019-01-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='滚动叫标题', max_length=225)),
                ('image', models.CharField(help_text='滚动条图片存储地址', max_length=225)),
            ],
            options={
                'db_table': 'ad',
            },
        ),
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='首页产品业务标题', max_length=225)),
                ('img', models.CharField(help_text='图标', max_length=225)),
                ('content', models.CharField(help_text='内容', max_length=225)),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(help_text='职位名称', max_length=225)),
                ('number', models.CharField(help_text='招聘人数', max_length=225)),
                ('time', models.DateTimeField(help_text='创建时间', max_length=225)),
                ('views', models.CharField(help_text='浏览量', max_length=225)),
                ('content', models.CharField(help_text='内容', max_length=225)),
                ('job_class_id', models.IntegerField(help_text='招聘状态')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='jobs_status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(help_text='状态', max_length=225)),
            ],
            options={
                'db_table': 'jobs_status',
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='姓名', max_length=30)),
                ('phone', models.CharField(help_text='电话', max_length=225)),
                ('email', models.EmailField(help_text='邮箱', max_length=254)),
                ('content', models.CharField(help_text='留言', max_length=225)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='新闻标题', max_length=225)),
                ('author', models.CharField(help_text='作者', max_length=225)),
                ('time', models.CharField(help_text='创建时间', max_length=225)),
                ('views', models.CharField(help_text='浏览量', max_length=225)),
                ('content', models.CharField(help_text='内容', max_length=225)),
                ('type_id', models.IntegerField(help_text='所属类别')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='news_class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='新闻类别', max_length=225)),
            ],
            options={
                'db_table': 'news_class',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='产品名称', max_length=225)),
                ('img', models.CharField(help_text='图标', max_length=225)),
                ('advantage', models.CharField(help_text='优势', max_length=225)),
                ('goods', models.CharField(help_text='抵押物', max_length=225)),
                ('money', models.CharField(help_text='最高可贷', max_length=225)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='视频标题', max_length=225)),
                ('video', models.CharField(help_text='视频地址', max_length=225)),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
