# Generated by Django 2.1.4 on 2019-01-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
